# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PhotoService.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12PhotoService.proto\x12\x15\x63om.photoService.grpc\"\x1e\n\x0ePhotoesRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\" \n\x0fPhotoesResponse\x12\r\n\x05image\x18\x01 \x01(\x0c\x32o\n\x0cPhotoService\x12_\n\x0erequestPhotoes\x12%.com.photoService.grpc.PhotoesRequest\x1a&.com.photoService.grpc.PhotoesResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PhotoService_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PHOTOESREQUEST._serialized_start=45
  _PHOTOESREQUEST._serialized_end=75
  _PHOTOESRESPONSE._serialized_start=77
  _PHOTOESRESPONSE._serialized_end=109
  _PHOTOSERVICE._serialized_start=111
  _PHOTOSERVICE._serialized_end=222
# @@protoc_insertion_point(module_scope)
