# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import PhotoService_pb2 as PhotoService__pb2


class PhotoServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.requestPhotoes = channel.unary_unary(
                '/com.photoService.grpc.PhotoService/requestPhotoes',
                request_serializer=PhotoService__pb2.PhotoesRequest.SerializeToString,
                response_deserializer=PhotoService__pb2.PhotoesResponse.FromString,
                )


class PhotoServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def requestPhotoes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PhotoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'requestPhotoes': grpc.unary_unary_rpc_method_handler(
                    servicer.requestPhotoes,
                    request_deserializer=PhotoService__pb2.PhotoesRequest.FromString,
                    response_serializer=PhotoService__pb2.PhotoesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.photoService.grpc.PhotoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PhotoService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def requestPhotoes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.photoService.grpc.PhotoService/requestPhotoes',
            PhotoService__pb2.PhotoesRequest.SerializeToString,
            PhotoService__pb2.PhotoesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
